### ISSUE TITLE
想做个把hdmi in推流到rtsp协议（摄像头、直播）的教程

### ISSUE THREAD

**Issue by CodeChenL** [radxa-docs/documentation#153]
不知道放在这个分类合不合适
![image](https://github.com/radxa-docs/documentation/assets/43897062/b9f0255b-71b2-4045-aef6-740f4a3c0335)

**Comment by RadxaYuntian** [comment]
先放到通用教程里面。HDMI IN无非就是个特殊一点的摄像头罢了

**Comment by CodeChenL** [comment]
但是官方rom的gstreamer貌似没有打支持rga的补丁

**Comment by CodeChenL** [comment]
mpp只接受nv12的输入源
如果输入源为RBG或者nv24等颜色格式就会报错不支持
这时候需要用到rk的硬件rga加速格式转换不然就是ppt

**Comment by CodeChenL** [comment]
使用armbian jammy
+rkmpp ppa的gstreamer可以正常使用rga
目前我使用的是debian，我尝试切换到官方ubuntu+rkmpp ppa试试

**Comment by CodeChenL** [comment]
![image](https://github.com/radxa-docs/documentation/assets/43897062/a33735b1-8025-4794-ba88-8e6aea76b5fd)
我发现已经调用了rga，但是还是卡，奇怪

**Comment by CodeChenL** [comment]
GST_VIDEO_CONVERT_USE_RGA=1 ./test-launch --gst-debug-level=3 "( v4l2src device=/dev/video0 ! videoconvert ! video/x-raw, width=1920, height=1080, format=NV16, framerate=60/1 ! queue ! mpph264enc bps=10240000 rc-mode=vbr !  rtph264pay name=pay0 pt=96 )"这是我的推流命令

**Comment by CodeChenL** [comment]
![image](https://github.com/radxa-docs/documentation/assets/43897062/0fe9eadd-a4f6-4709-a524-2efe6b3bc060)

能否把mpp和gstreamer升级为最新的厂商版本，我看到好像支持nv24了，那就可以适配设备了（一般默认就是nv24）

**Comment by RadxaYuntian** [comment]
> ~使用armbian jammy +rkmpp ppa的gstreamer可以正常使用rga 目前我使用的是debian，我尝试切换到官方ubuntu+rkmpp ppa试试~

我们的文档目前只介绍基于我们Debian系统的应用。其他的系统我们没法支持

**Comment by RadxaYuntian** [comment]
> 能否把mpp和gstreamer升级为最新的厂商版本，我看到好像支持nv24了，那就可以适配大多数设备了（一般默认就是nv24）

这个要按照我们的SDK升级进度来，不然版本不匹配不方便从Rockchip获得技术支持。

**Comment by CodeChenL** [comment]
> > ~使用armbian jammy +rkmpp ppa的gstreamer可以正常使用rga 目前我使用的是debian，我尝试切换到官方ubuntu+rkmpp ppa试试~
> 
> 我们的文档目前只介绍基于我们Debian系统的应用。其他的系统我们没法支持

嗯，我现在使用的就是debian在做，因为我发现其他系统也一样（
