### ISSUE TITLE
新添加的内容会在英文页面上显示中文sidebar label

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/documentation#154]
https://docs.radxa.com/en/radxa-os/peripherals
![image](https://github.com/radxa-docs/documentation/assets/95260730/7c95fef4-2d0d-4d32-84a1-77599cbf657a)

**Comment by Maycides** [comment]
#161

**Comment by RadxaYuntian** [comment]
应该是直接在PR的说明里写`This PR fixes #154`. 这样的话合并后会自动关闭这个issue

**Comment by jack-ma** [comment]
4G 模组的应用教程，应该放到 accessory 大类下。

**Comment by Maycides** [comment]
Fixed.
