### ISSUE TITLE
添加修改内核命令以及关闭串口终端的说明

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/documentation#187]
https://wiki.radxa.com/Rockpi4/dev/use-uart2-as-application-uart

**Comment by Maycides** [comment]
这个是仅限于4系列的吗

**Comment by RadxaYuntian** [comment]
是个通用教程

**Comment by CodeChenL** [comment]
这个教程还要写吗，我发现dtbo没有关闭fiq-debuger，我可以写一个

**Comment by CodeChenL** [comment]
> 这个教程还要写吗，我发现dtbo没有关闭fiq-debuger，我可以写一个dtbo

**Comment by RadxaYuntian** [comment]
fiq-debugger一般是在我们uart2的overlay里面就关了：https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m0.dts

**Comment by CodeChenL** [comment]
原来在这，那我周末写一个教程？

**Comment by RadxaYuntian** [comment]
好的，麻烦了

**Comment by CodeChenL** [comment]
这个问题可以关闭了吧

**Comment by RadxaYuntian** [comment]
当时想的是有两个页面，一个讲怎么修改内核命令（/etc/kernel/cmdline），一个关闭串口终端（引用上一个页面）

**Comment by CodeChenL** [comment]
那我有空再优化一下

**Comment by CodeChenL** [comment]
这个issue应该可以关闭了？

**Comment by RadxaYuntian** [comment]
你现在还能在我们目前的文档中找到这个内容么

**Comment by CodeChenL** [comment]
https://docs.radxa.com/rock5/rock5b/os-config/rsetup#%E5%B0%86-uart2_m0-%E9%85%8D%E7%BD%AE%E4%B8%BA%E6%99%AE%E9%80%9A%E4%B8%B2%E5%8F%A3
和
https://docs.radxa.com/rock5/rock5b/os-config/bootparam
