### ISSUE TITLE
最近发现了一个支持rkmpp的ffmpeg库

### ISSUE THREAD

**Issue by CodeChenL** [radxa-docs/documentation#191]
ffmpeg生态会更好一点
想和目前doc里的 #164 一样做个教程
想讨论一下，是新开一页还是写在一起比较好？

**Comment by RadxaYuntian** [comment]
Jellyfin的ffmpeg么？新开一个页面吧

**Comment by CodeChenL** [comment]
> Jellyfin的ffmpeg么？新开一个页面吧

https://github.com/jjm2473/ffmpeg-rk还要下游，支持会更好

**Comment by RadxaYuntian** [comment]
是不是 https://github.com/hbiyik/FFmpeg/ 会更好一点

**Comment by CodeChenL** [comment]
嗯，都可以试试，不过这个库[https://github.com/jjm2473/ffmpeg-rk/wiki](https://github.com/jjm2473/ffmpeg-rk/wiki)，作者已经帮忙踩Jellyfin的坑了,不知道[https://github.com/hbiyik/FFmpeg/](https://github.com/hbiyik/FFmpeg/)的和Jellyfin的适配度高不高

> 是不是 https://github.com/hbiyik/FFmpeg/ 会更好一点

**Comment by RadxaYuntian** [comment]
Jellyfin他直接提供了docker镜像，可以不管。按照他自己项目的说明，[hbiyik/FFmpeg](https://github.com/hbiyik/FFmpeg/)更适合用于桌面系统

**Comment by CodeChenL** [comment]
![573576c38b7242d93378a73ef337750f](https://github.com/radxa-docs/documentation/assets/43897062/94f3b129-24c6-476a-be7d-612a96da5986)
![6130db4354737ac765ac5fcc257d154c](https://github.com/radxa-docs/documentation/assets/43897062/d22e5e1a-486d-4fe9-b074-4291b3482a0d)
可能需要你们修改一下设备树的cms大小

**Comment by CodeChenL** [comment]
armbian有另外的错误，我试试另一个库

**Comment by CodeChenL** [comment]
好消息，实一直是权限问题，sudo就好了
奇怪了，我已经按照给的要求加入video用户组了
做梦也没想到卡到这里，哈哈

**Comment by CodeChenL** [comment]
支持很不错啊，甚至比gst支持的格式多

**Comment by RadxaYuntian** [comment]
> 好消息，其实一直是权限问题，sudo就好了 奇怪了，我已经按照给的要求加入video用户组了 做梦也没想到卡到这里，哈哈

可能是/dev/video0之类的没有分配到video组里面：https://github.com/radxa-pkg/rockchip-udev/blob/main/debian/rockchip-udev.rockchip-permissions.udev

**Comment by CodeChenL** [comment]
> > 好消息，其实一直是权限问题，sudo就好了 奇怪了，我已经按照给的要求加入video用户组了 做梦也没想到卡到这里，哈哈
> 
> 可能是/dev/video0之类的没有分配到video组里面：https://github.com/radxa-pkg/rockchip-udev/blob/main/debian/rockchip-udev.rockchip-permissions.udev
应该是dma的用户组权限问题
```
rock@rock-5b:~$ ls -l /dev/dri /dev/dma_heap
/dev/dma_heap:
total 0
crw------- 1 root root 251, 4 Dec 22  2022 cma
crw------- 1 root root 251, 5 Dec 22  2022 cma-uncached
crw------- 1 root root 251, 0 Dec 22  2022 system
crw------- 1 root root 251, 1 Dec 22  2022 system-dma32
crw------- 1 root root 251, 2 Dec 22  2022 system-uncached
crw------- 1 root root 251, 3 Dec 22  2022 system-uncached-dma32

/dev/dri:
total 0
drwxr-xr-x  2 root root        120 Dec 22  2022 by-path
crw-rw----+ 1 root video  226,   0 Dec 22  2022 card0
crw-rw----+ 1 root video  226,   1 Dec 22  2022 card1
crw-rw----+ 1 root render 226, 128 Dec 22  2022 renderD128
crw-rw----+ 1 root render 226, 129 Dec 22  2022 renderD129
rock@rock-5b:~$ 
```

**Comment by CodeChenL** [comment]
奇怪的是我重新刷写了系统镜像，然后重复操作现在又不行了

**Comment by CodeChenL** [comment]
确定问题了，编译最新mpp的so就行了。
@RadxaYuntian 请问我是写在教程里还是等你们更新mpp

**Comment by RadxaYuntian** [comment]
我们现在mpp是跟着rockchip sdk一起走的，单独更新可能会有别的问题

**Comment by CodeChenL** [comment]
那我把编译最新mpp的方法放到教程里吧
