### ISSUE TITLE
打算写点跑官方NPU例程的教程

### ISSUE THREAD

**Issue by CodeChenL** [radxa-docs/documentation#204]
打算跑[这个](https://github.com/rockchip-linux/rknn-toolkit2/tree/master/examples/tensorflow/ssd_mobilenet_v1)例程
请问放在哪个路径合适

**Comment by CodeChenL** [comment]
上面的链接是在linux pc跑模拟器或者连板调试，除此之外我还想写在板端跑的C和python接口的例程教程

**Comment by RadxaYuntian** [comment]
通用教程那里吧

**Comment by RadxaYuntian** [comment]
回头要整理一下目录结构

**Comment by RadxaYuntian** [comment]
5B是的

**Comment by CodeChenL** [comment]
> 5B是的

那还得买个hub啊，汤亮哥之前不是在微信群说改到普通usb a口吗

**Comment by RadxaYuntian** [comment]
那会是个升级版吧

**Comment by CodeChenL** [comment]
> 那会是个升级版吧

你的意思是新的硬件版本吗，这是tom原文
![Screenshot_2023-08-30-12-20-10-034_com tencent mm](https://github.com/radxa-docs/documentation/assets/43897062/e96e19a5-b466-4ce3-bfeb-ee9b2bfc263b)

**Comment by RadxaYuntian** [comment]
@RadxaStephen 所以这个dtb到底改了么？

**Comment by CodeChenL** [comment]
adb使用的端口有结果了吗

**Comment by RadxaYuntian** [comment]
@RadxaStephen 所以这个dtb到底改了么？

另外板端的rknn2我这边刚刚做好了打包，在5A上测试通过。之后会修改[vendor-profiles](https://github.com/radxa-pkg/vendor-profiles/blob/main/debian/control#L189)把运行时自动安装到我们的系统里。

**Comment by CodeChenL** [comment]
> @RadxaStephen 所以这个dtb到底改了么？
> 
> 另外板端的rknn2我这边刚刚做好了打包，在5A上测试通过。之后会修改[vendor-profiles](https://github.com/radxa-pkg/vendor-profiles/blob/main/debian/control#L189)把运行时自动安装到我们的系统里。

那我也要改改文档的安装方式了

**Comment by CodeChenL** [comment]
> > @RadxaStephen 所以这个dtb到底改了么？
> > 另外板端的rknn2我这边刚刚做好了打包，在5A上测试通过。之后会修改[vendor-profiles](https://github.com/radxa-pkg/vendor-profiles/blob/main/debian/control#L189)把运行时自动安装到我们的系统里。
> 
>好的， 那我也要改改文档的安装方式了

**Comment by RadxaYuntian** [comment]
忘了带上rknn2的链接了：https://github.com/radxa-pkg/rknn2/releases
vendor-profiles已经改好了，只有 python3-rknnlite2-example是不会自动安装的。如果需要测试装这个包，然后：
```bash
cd /usr/share/python3-rknnlite2
python3 test.py
```
就好。Rockchip的代码写的只能检索当前目录里面的模型，所以必须cd过去

**Comment by CodeChenL** [comment]
> 

好的

**Comment by CodeChenL** [comment]
> 忘了带上rknn2的链接了：https://github.com/radxa-pkg/rknn2/releases vendor-profiles已经改好了，只有 python3-rknnlite2-example是不会自动安装的。如果需要测试装这个包，然后：
> 
> ```shell
> cd /usr/share/python3-rknnlite2
> python3 test.py
> ```
> 
> 就好。Rockchip的代码写的只能检索当前目录里面的模型，所以必须cd过去

不建议用最新版本的rknn 和 rknn-toolkit-lite2，因为会警告与内核驱动版本不匹配（虽然也能用）

**Comment by CodeChenL** [comment]
@RadxaStephen @RadxaYuntian 我买了一个带pd供电的hub还是无法识别到adb设备，一定要usb数据线直连吗

**Comment by CodeChenL** [comment]
用带pd的pc usb接口会反复重启，普通接口供电不足，高负载也会重启

**Comment by CodeChenL** [comment]
> 用带pd的pc usb接口会反复重启，普通接口供电不足也会重启

**Comment by CodeChenL** [comment]
貌似是内核自己重启，电脑usb并没有强制断电，因为我加了pd欺骗器，5b端还用的usb2数据线根本没有cc引脚

**Comment by CodeChenL** [comment]
反复打印这段日志
```
DDR V1.11 f1474cf52f cym 23/05/09-11:02:36
LPDDR4X, 2112MHz
channel[0] BW=16 Col=10 Bk=8 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=2048MB
channel[1] BW=16 Col=10 Bk=8 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=2048MB
channel[2] BW=16 Col=10 Bk=8 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=2048MB
channel[3] BW=16 Col=10 Bk=8 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=2048MB
Manufacturer ID:0x6
CH0 RX Vref:31.0%, TX Vref:23.8%,22.8%
CH1 RX Vref:27.5%, TX Vref:22.8%,22.8%
CH2 RX Vref:29.7%, TX Vref:22.8%,21.8%
CH3 RX Vref:31.4%, TX Vref:22.8%,23.8%
change to F1: 528MHz
change to F2: 1068MHz
change to F3: 1560MHz
change to F0: 2112MHz
out
INFO:    Preloader serial: 2
NOTICE:  BL31: v2.3():v2.3-589-g3389cfdda:derrick.huang
NOTICE:  BL31: Built : 10:14:29, May  9 2023
INFO:    spec: 0x1
INFO:    ext 32k is not valid
INFO:    ddr: stride-en 4CH
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    valid_cpu_msk=0xff bcore0_rst = 0x0, bcore1_rst = 0x0
INFO:    system boots from cpu-hwid-0
INFO:    idle_st=0x21fff, pd_st=0x11fff9, repair_st=0xfff70001
INFO:    dfs DDR fsp_params[0].freq_mhz= 2112MHz
INFO:    dfs DDR fsp_params[1].freq_mhz= 528MHz
INFO:    dfs DDR fsp_params[2].freq_mhz= 1068MHz
INFO:    dfs DDR fsp_params[3].freq_mhz= 1560MHz
INFO:    BL31: Initialising Exception Handling Framework
INFO:    BL31: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s destined for OPTEE will return SMC_UNK
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x200000
INFO:    SPSR = 0x3c9
```
当我把pd欺骗器设置为9v及以上挡位才能启动，但是我的pc pd最高只支持5v

**Comment by CodeChenL** [comment]
看起来是输入5b的电压是5v的话，5b自己会自动重启？

**Comment by CodeChenL** [comment]
这样的话typec口作为adb就不合理啊

**Comment by RadxaYuntian** [comment]
5B的PD是有些问题。所以 @RadxaStephen 所以这个dtb到底改了么？

**Comment by CodeChenL** [comment]
这个issue能reopen一下吗，其实还没完，还有连板调试没写

**Comment by RadxaYuntian** [comment]
@RadxaStephen 告诉我硬件设计上有些问题，没法在现有产品上把otg迁移到a口

**Comment by CodeChenL** [comment]
我用带PD供电的hub接入 5b的typec口，pc也不识别，应该是因为不符合usb协议？hub只能传输host信号而不能传输Device信号

**Comment by CodeChenL** [comment]
那5b的OTG接口看起来基本没用啦，只能链接rkdevtool。
能不能让5b输入5v时不自动重启呢

**Comment by CodeChenL** [comment]
能不能让他支持5v pd呢，很多笔记本的pd输出只有5v这一档

**Comment by CodeChenL** [comment]
看起来无解了，我先关闭issues了

**Comment by CodeChenL** [comment]
![image](https://github.com/radxa-docs/documentation/assets/43897062/15936a8d-ef2d-45de-a053-f70ff5fd056b)
我看群里有人5v怼GPIO也启动不了？

**Comment by RadxaYuntian** [comment]
群里叫了没反应。
这个issue也不是供电相关的，先关了
