### ISSUE TITLE
是不是把首页直接干掉算了？

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/documentation#214]
改成 https://docs.radxa.com/welcome 直接进入文档

#209 f1eb3b15dbdfdff0c5d97d9ee17170af87185f61 @xzuoqi 说 [没问题](https://github.com/radxa-docs/documentation/pull/209#pullrequestreview-1606472665) 但现在首页显示异常了：

![image](https://github.com/radxa-docs/documentation/assets/95260730/31bad17a-cc5e-4c5e-80e9-ac311e2783dc)

这个页面我一直觉得多余，要不干脆就不要了？

**Comment by logan-milkv** [comment]
我先把css改回来吧，这个页面melo说先不动
