### ISSUE TITLE
开源GPU驱动编译教程

### ISSUE THREAD

**Issue by CodeChenL** [radxa-docs/documentation#231]
使用此库https://gitlab.com/panfork/mesa
请问是否接受pr？
虽然是重复工作，但是一般用户比较难找到，经过我的测试，该项目文档也有些疏漏需要补充

**Comment by RadxaYuntian** [comment]
我比较担心这个编译成功后如何在我们发布的镜像上面使用。我现在在ROCK 4上开启panfrost关闭mali后系统就直接无法启动了

**Comment by CodeChenL** [comment]
这个库主要是用于rk3588的吧，rk3399和rk3368的panfrost都已经并入mesa主线了

**Comment by RadxaYuntian** [comment]
但是担心同样会有启动问题

**Comment by CodeChenL** [comment]
![image](https://github.com/radxa-docs/documentation/assets/43897062/a0de8b53-c2ef-4ec4-8bdf-a6c56cdbe00d)

**Comment by CodeChenL** [comment]
> 但是担心同样会有启动问题

我可以测试一下

**Comment by RadxaYuntian** [comment]
那麻烦了

**Comment by CodeChenL** [comment]
就是重启一下有什么麻烦的，目前我是远程ssh编译的，等我回到宿舍重启试试

**Comment by CodeChenL** [comment]
成功，你应该是少了libdri2to3、换主线xserver或者设置panfrost相关so的优先度
![image](https://github.com/radxa-docs/documentation/assets/43897062/3f8e3696-c144-4f97-81f9-d0a6c6d5d181)

**Comment by RadxaYuntian** [comment]
那麻烦先提个pr吧，我之后再看看rock 4是怎么回事

**Comment by CodeChenL** [comment]
好的，不过据我了解356x和3399用的是主线mesa，这个魔改库主要是兼容3588的，不知道兼不兼容前两者

**Comment by RadxaYuntian** [comment]
是这样的，但我主要关心是之前开启panfrost驱动后直接系统没法进桌面，所以还没到mesa那边

**Comment by CodeChenL** [comment]
> 我比较担心这个编译成功后如何在我们发布的镜像上面使用。我现在在ROCK 4上开启panfrost关闭mali后系统就直接无法启动了

我曾经在rock 4b上开启过panfrost，可惜我把rock 4b出了，买了rock 5b
