### ISSUE TITLE
备份脚本更新

### ISSUE THREAD

**Issue by CodeChenL** [radxa-docs/documentation#234]
请问@Ken-Vamrs是radxa员工吗，能否提醒一下他更新一下上游改动https://github.com/Ken-Vamrs/rockpi-toolkit ，我提交了一个致命错误的PR https://github.com/akgnah/rockpi-toolkit/issues/9  https://github.com/akgnah/rockpi-toolkit/pull/10 ，官网文档https://docs.radxa.com/general-tutorial/image-backup 用的是@Ken-Vamrs的库

**Comment by RadxaYuntian** [comment]
他那边有问题去他那个仓库提issue啊……你在那边也可以at我的
@akgnah 是不是把akgnah/rockpi-toolkit移动到radxa组织下好一点，不要放个人仓库在我们的文档里

**Comment by RadxaYuntian** [comment]
而且我记得当时是说老的debos镜像一个备份脚本，新的rbuild镜像一个备份脚本。不知道你们现在这边是什么情况

**Comment by CodeChenL** [comment]
> 而且我记得当时是说老的debos镜像一个备份脚本，新的rbuild镜像一个备份脚本。不知道你们现在这边是什么情况

和你说的情况一样

**Comment by CodeChenL** [comment]
@Ken-Vamrs已更新
