### ISSUE TITLE
添加手动安装overlay的文档

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/documentation#261]

**Comment by CodeChenL** [comment]
我pr里的add-led文档貌似可以直接用？不需要再新增文档

**Comment by RadxaYuntian** [comment]
这个issue更多是希望介绍如何从[radxa/overlays](https://github.com/radxa/overlays/actions/runs/6542043637)安装CI生成的overlay以及下载源码后通过它自己的makefile进行编译后安装

**Comment by CodeChenL** [comment]
![image](https://github.com/radxa-docs/documentation/assets/43897062/093bf102-790d-4896-9f02-7b8e0d341308)
你希望吧这些dtbo的后缀改成.disabled,通过rsetup启用。
还是手写extlinux.conf启用

**Comment by RadxaYuntian** [comment]
用户一般安装一个overlay就是希望立刻启用的，所以只需要复制过去后执行`sudo u-boot-update`即可

**Comment by CodeChenL** [comment]
```bash
rock@rock-5b:~$ cat /etc/default/u-boot
## /etc/default/u-boot - configuration file for u-boot-update(8)

#U_BOOT_UPDATE="true"

#U_BOOT_ALTERNATIVES="default recovery"
#U_BOOT_DEFAULT="l0"
#U_BOOT_ENTRIES="all"
#U_BOOT_MENU_LABEL="Debian GNU/Linux"
#U_BOOT_PARAMETERS="ro quiet"
#U_BOOT_ROOT=""
#U_BOOT_TIMEOUT="50"
#U_BOOT_FDT=""
#U_BOOT_FDT_DIR="/usr/lib/linux-image-"
#U_BOOT_FDT_OVERLAYS=""
#U_BOOT_FDT_OVERLAYS_DIR="/boot/dtbo/"

U_BOOT_TIMEOUT="10"
U_BOOT_PARAMETERS="$(cat /etc/kernel/cmdline)"
U_BOOT_FDT_DIR="/usr/lib/linux-image-"
rock@rock-5b:~$ 
```
设置`U_BOOT_FDT_OVERLAYS`这个变量，然后运行`sudo u-boot-update`是吗。
多个dtbo用空格分隔？

**Comment by RadxaYuntian** [comment]
u-boot-update里面有一个默认值，也会自己source这个配置文件。把dtbo全部复制到/boot/dtbo/后直接运行就好，没有额外参数

**Comment by RadxaYuntian** [comment]
看看是不是可以关了

**Comment by CodeChenL** [comment]
[on ROCK 5B and Orange Pi 5, the top USB 3.0 Type-A port only supports SuperSpeed (3.0) devices (so mouse & keyboard won't work). The other USB 3 ports are limited to 2.0 speeds.](https://docs.radxa.com/rock5/rock5b/os-config/rsetup#overlays)
