### ISSUE TITLE
添加vendor gpio转换成libgpiod的方法

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/documentation#319]
主要面向CM用户，需要使用非底板上的gpio

**Comment by nascs** [comment]
gpiod 的 chip 和 RK 的 BANK 的对应关系以及 gpiod 的 line 和 RK 的 RK_PXX 对应关系？

**Comment by RadxaYuntian** [comment]
应该是这个意思

**Comment by RadxaYuntian** [comment]
另外要注意我们还有amlogic和其他厂商的soc,页面在编写时不要过于rockchip中心了

**Comment by nascs** [comment]
这就有点不太好写了，
rockchip 是 TRM 有介绍，
amlogic 在内核源码头文件中有，linux/include/dt-bindings/gpio/meson-*.h
intel 是内核驱动源码中 drivers/pinctrl/intel/xxx.c

**Comment by RadxaYuntian** [comment]
用tab区分。另外rockchip也去引用内核头文件，不然用户就会问问什么rk3399要去看rk3588的trm

**Comment by RadxaYuntian** [comment]
能关了么

**Comment by nascs** [comment]
可以关了，pr 已经合并了
