### ISSUE TITLE
RadxaOS 测试仓库开启脚本没有更改仓库链接

### ISSUE THREAD

**Issue by zy5426** [radxa-docs/documentation#329]
https://docs.radxa.com/radxa-os/maintenance/apt-repo?test-repo=enable#radxaos-%E6%B5%8B%E8%AF%95%E4%BB%93%E5%BA%93

**Comment by RadxaYuntian** [comment]
已于 2cc8a4815cddde046f406102778e184aa13600a6 中修复。
