### ISSUE TITLE
Edit button should jump to the correct language edit page

### ISSUE THREAD

**Issue by jack-ma** [radxa-docs/documentation#370]
Click the edit button on the English page should edit the en version .md file.

**Comment by RadxaYuntian** [comment]
@xzuoqi https://github.com/radxa-docs/documentation/commit/4a8cb19c7fd6c675d4c5f294b25d032ad2a5c4a0 is a hack. Should follow the official documentation.

**Comment by xzuoqi** [comment]
> https://docusaurus.io/docs/next/i18n/git#localize-edit-urls

这个方法适用过了，只是不能达到理想功能，可能是我使用方法不对？

**Comment by xzuoqi** [comment]
> @xzuoqi [4a8cb19](https://github.com/radxa-docs/documentation/commit/4a8cb19c7fd6c675d4c5f294b25d032ad2a5c4a0) is a hack. Should follow the official documentation.

官方文档推荐方法没达到预期效果，所以换了一个实现思路

**Comment by RadxaYuntian** [comment]
所以具体的表现是咋样

**Comment by RadxaYuntian** [comment]
目前可以正常工作
