### ISSUE TITLE
5B GPIO pin 37没有标注

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/documentation#542]
需要验证是否是没有硬件连接

https://docs.radxa.com/en/rock5/rock5b/hardware/rock5b-gpio

**Comment by nascs** [comment]
这个 issue 可以关了， [pr 586](https://github.com/radxa-docs/documentation/pull/586) 已合并

**Comment by RadxaYuntian** [comment]
可以在PR的正文里面写`Fixes #542`，这样当PR合并时这个issue也会自动关闭

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
